version: 1.0.{build}-{branch}
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
configuration: Release
platform: Any CPU
build:
  verbosity: normal
deploy:
- provider: GitHub
  tag: hash-calc-v$(appveyor_build_version)
  release: File Hash Calculator -
  auth_token:
    secure: 7MeZ9kNY6n5afecuSS0NRPrIW5LCno+vmA4/mUlgh33UTVbrFqzcFIdBEWsTu7r7
  on:
    branch: master